# Generated by Django 6.0 on 2025-12-13 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_rename_comment_commentary_rename_user_post_owner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="owner",
            new_name="author",
        ),
    ]
