# Generated by Django 6.0 on 2025-12-13 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_rename_owner_post_author"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commentary",
            options={"ordering": ["-created_date"]},
        ),
        migrations.RenameField(
            model_name="commentary",
            old_name="user",
            new_name="author",
        ),
        migrations.RenameField(
            model_name="commentary",
            old_name="created_time",
            new_name="created_date",
        ),
        migrations.RenameField(
            model_name="commentary",
            old_name="content",
            new_name="text",
        ),
    ]
