# Generated by Django 6.0 on 2025-12-13 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_commentary_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Commentary",
            new_name="Comment",
        ),
    ]
