# Generated by Django 6.0 on 2025-12-13 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_rename_author_post_owner_commentary_delete_comment"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Commentary",
            new_name="Comment",
        ),
    ]
