# Generated by Django 6.0 on 2025-12-13 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_rename_commentary_comment"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Comment",
            new_name="Commentary",
        ),
    ]
